// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_miBbQ09XK4ZQMozIr38Hv6Vlb1ASxtg',
    appId: '1:501142649852:web:8c043568da0afeed2e5079',
    messagingSenderId: '501142649852',
    projectId: 'lumiere-flow',
    authDomain: 'lumiere-flow.firebaseapp.com',
    storageBucket: 'lumiere-flow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KOiiJAtdCQsLMChfaatThDFI2HMbFAc',
    appId: '1:501142649852:android:74324c408fe5f0ab2e5079',
    messagingSenderId: '501142649852',
    projectId: 'lumiere-flow',
    storageBucket: 'lumiere-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nFWfkHc3PUq7ht9CIvy26Z_Bwbw7FAc',
    appId: '1:501142649852:ios:8eacd03f25b8e3652e5079',
    messagingSenderId: '501142649852',
    projectId: 'lumiere-flow',
    storageBucket: 'lumiere-flow.firebasestorage.app',
    iosBundleId: 'com.example.lumiereFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nFWfkHc3PUq7ht9CIvy26Z_Bwbw7FAc',
    appId: '1:501142649852:ios:8eacd03f25b8e3652e5079',
    messagingSenderId: '501142649852',
    projectId: 'lumiere-flow',
    storageBucket: 'lumiere-flow.firebasestorage.app',
    iosBundleId: 'com.example.lumiereFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_miBbQ09XK4ZQMozIr38Hv6Vlb1ASxtg',
    appId: '1:501142649852:web:446d7b5b57db4f702e5079',
    messagingSenderId: '501142649852',
    projectId: 'lumiere-flow',
    authDomain: 'lumiere-flow.firebaseapp.com',
    storageBucket: 'lumiere-flow.firebasestorage.app',
  );
}
